# Generated by Django 4.0 on 2022-02-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('pfrom', models.CharField(max_length=64)),
                ('pto', models.CharField(max_length=64)),
                ('phone', models.IntegerField()),
                ('jdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('tfrom', models.CharField(max_length=64)),
                ('tto', models.CharField(max_length=64)),
                ('jdate', models.DateField()),
                ('phone', models.IntegerField()),
                ('tveh', models.CharField(max_length=64)),
            ],
        ),
    ]
